"""create all tables

Revision ID: 83fbd3008b58
Revises: 
Create Date: 2026-06-26 22:49:16.563642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83fbd3008b58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_inventory',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('item_budget', sa.Float(), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('master_merchants',
    sa.Column('merchant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_name', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('on_time_history', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('merchant_id'),
    sa.UniqueConstraint('merchant_name')
    )
    op.create_table('transaction_audit_logs',
    sa.Column('audit_log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trn_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default='extracted', nullable=False),
    sa.Column('review_note', sa.Text(), server_default='Invoice extracted', nullable=False),
    sa.Column('reviewed_by', sa.Text(), server_default='Maker', nullable=False),
    sa.Column('payment_txn_id', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Date(), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.PrimaryKeyConstraint('audit_log_id')
    )
    op.create_table('transaction_invoice_items',
    sa.Column('invoice_transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trn_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('line_total', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('invoice_transaction_id')
    )
    op.create_table('transaction_invoices',
    sa.Column('trn_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_number', sa.Text(), nullable=False),
    sa.Column('merchant_id', sa.Text(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('trn_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_invoices')
    op.drop_table('transaction_invoice_items')
    op.drop_table('transaction_audit_logs')
    op.drop_table('master_merchants')
    op.drop_table('master_inventory')
    # ### end Alembic commands ###
